### ISSUE TITLE
Docker Run Command pulling from docker hub not working.

### ISSUE THREAD

**Issue by iamk3** [jjohnson338/docker-buckets#1]
Did you compile this for a specific architecture? Using the docker run, I can't get the container to come up.

docker run --rm -p 5800:5800 -p 5900:5900 -v C:\path\to\.docker\buckets-trial\config:/config docker-buckets

Logs where it gets weird:
`[15:30:49.326] [info] (core) ERROR (appwide) keyring.getPassword failed: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[15:30:49.327] [info] (core) ERROR (sharing) encrypting seckey failed: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[15:30:49.327] [info] (core) ERROR (peddler) error creating peddler Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
(node:838) UnhandledPromiseRejectionWarning: Error: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
    at BucketsBackendRPCWrap.<anonymous> (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:128:40)
    at step (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:33:23)
    at Object.next (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:14:53)
    at /opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:4:12)
    at BucketsBackendRPCWrap.rpcResultReceived (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:119:16)
    at BucketsBackendRPCWrap.<anonymous> (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:112:26)
    at step (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:33:23)
    at Object.next (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:14:53)
    at /opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:4:12)
    at BucketsBackendRPCWrap.handleSingleBackendMessage (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:104:16)
    at BucketsBackendRPCWrap.<anonymous> (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:97:56)
    at step (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:33:23)
    at Object.next (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:14:53)
    at /opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:4:12)
    at BucketsBackendRPCWrap.handleBackendOutput (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:82:16)
    at NetstringParser.handler (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-node/dist/main.js:223:35)
(node:838) UnhandledPromiseRejectionWarning: Error: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
    at BucketsBackendRPCWrap.<anonymous> (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:128:40)
    at step (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:33:23)
    at Object.next (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:14:53)
    at /opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:4:12)
    at BucketsBackendRPCWrap.rpcResultReceived (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:119:16)
    at BucketsBackendRPCWrap.<anonymous> (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:112:26)
    at step (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:33:23)
    at Object.next (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:14:53)
    at /opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:4:12)
    at BucketsBackendRPCWrap.handleSingleBackendMessage (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:104:16)
    at BucketsBackendRPCWrap.<anonymous> (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:97:56)
    at step (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:33:23)
    at Object.next (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:14:53)
    at /opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:4:12)
    at BucketsBackendRPCWrap.handleBackendOutput (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-common/dist/src/backend-base.js:82:16)
    at NetstringParser.handler (/opt/Buckets Beta/resources/app.asar/node_modules/buckets-node/dist/main.js:223:35)
(node:838) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:838) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:838) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:838) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[15:30:49.338] [info] (main) window opened to file:///opt/Buckets%20Beta/resources/app.asar/src/wwwroot/misc/wizard.html
[15:30:49.339] [info] (drm) Will nag starting 2022-07-06T15:30:49+00:00
[909:0106/153050.235127:FATAL:memory.cc(22)] Out of memory. size=13516800
[891:0106/153050.274833:ERROR:gles2_cmd_decoder.cc(18538)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCreateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
[891:0106/153050.274901:ERROR:gles2_cmd_decoder.cc(18559)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeginSharedImageAccessCHROMIUM: bound texture is not a shared image
[891:0106/153050.276890:ERROR:gles2_cmd_decoder.cc(10749)] [.DisplayCompositor]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[891:0106/153050.317914:ERROR:gles2_cmd_decoder.cc(18582)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoEndSharedImageAccessCHROMIUM: bound texture is not a shared image
[891:0106/153050.317977:ERROR:gles2_cmd_decoder.cc(18538)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCreateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
[891:0106/153050.317986:ERROR:gles2_cmd_decoder.cc(18559)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeginSharedImageAccessCHROMIUM: bound texture is not a shared image
[891:0106/153050.318022:ERROR:gles2_cmd_decoder.cc(10749)] [.DisplayCompositor]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[891:0106/153050.318230:ERROR:gles2_cmd_decoder.cc(18582)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoEndSharedImageAccessCHROMIUM: bound texture is not a shared image`

Any assistance would be appreciated.

**Comment by jjohnson338** [comment]
I remember seeing a keyring issue similar to this previously. IIRC I think this was related to the electron options. Which is why I added the following flags to the buckets command (which are passed through to electron):
https://github.com/jjohnson338/docker-buckets/blob/233c7ecd7c4b9d41e9b4b670d3cdc92bc7cc3d44/startapp.sh#L3
